### ISSUE TITLE
is not found HtmlTemplate.java

### ISSUE THREAD

**Issue by fqtyfz** [lutece-platform/lutece-core#51]
is not found  fr.paris.lutece.util.html.HtmlTemplate.java

**Comment by fqtyfz** [comment]
nobody?

**Comment by rzara** [comment]
Hi,
This class is to be found in the library-freemarker component. This project has not yet been migrated to github, but you can view the source there : http://dev.lutece.paris.fr/svn/lutece/portal/trunk/plugins/library/library-freemarker/

**Comment by fqtyfz** [comment]
ok ,
is right ,very thank !
